package postgres

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/MoYuanCN/Jelee/internal/adapter/nfo"
	"github.com/MoYuanCN/Jelee/internal/app"
	"github.com/MoYuanCN/Jelee/internal/domain"
	"github.com/MoYuanCN/Jelee/internal/platform/resources"
)

func nfoWritePreparationFixture(t *testing.T) (jobFixture, *app.NFOWritePreparations, domain.NFOItemScope, domain.NFOWritePrepareRequest) {
	t.Helper()
	f, scope, _ := nfoItemApplyFixture(t)
	if err := os.WriteFile(filepath.Join(scope.Source.RootPath, scope.Source.RelativePath), []byte("\xef\xbb\xbf<movie x='keep'>\r\n  <title>old</title><!--keep-->\r\n  <vendor a='1'/>\r\n</movie>"), 0600); err != nil {
		t.Fatal("create private NFO fixture")
	}
	b, _ := resources.New(resources.Limits{CPU: 1, IO: 1, Total: 1, Queue: 32})
	p, _ := nfo.NewWritePreparer(b)
	service, _ := app.NewNFOWritePreparations(f.s, p)
	request := domain.NFOWritePrepareRequest{ItemID: scope.ItemID, Revision: scope.Revision, Edits: []domain.NFOWriteTextEdit{{Field: "title", Value: "新標題"}}, MaxBytes: domain.NFODefaultSourceBytes, Backups: 3, BOM: "preserve"}
	return f, service, scope, request
}

func TestNFOWritePreparationPersistsControlledOutputAndExactReplay(t *testing.T) {
	f, service, scope, request := nfoWritePreparationFixture(t)
	before, _ := os.ReadFile(filepath.Join(scope.Source.RootPath, scope.Source.RelativePath))
	prepared, replay, err := service.Prepare(f.ctx, f.a, "freeze-output", request)
	if err != nil || replay || !domain.ValidID(prepared.ID) || domain.ValidateNFOWritePreparation(prepared) != nil || !prepared.ExpiresAt.Equal(prepared.CreatedAt.Add(domain.NFORequestRetention)) {
		t.Fatal("preparation failed or retention differs")
	}
	if !bytes.Equal(prepared.Original, before) || !bytes.HasPrefix(prepared.Replacement, []byte{0xef, 0xbb, 0xbf}) || !bytes.Contains(prepared.Replacement, []byte("<!--keep-->")) || !bytes.Contains(prepared.Replacement, []byte("<vendor a='1'/>")) || !bytes.Contains(prepared.Replacement, []byte("\r\n")) {
		t.Fatal("original or retained XML changed")
	}
	doc, err := nfo.Read(f.ctx, bytes.NewReader(prepared.Replacement), request.MaxBytes)
	if err != nil || doc.Entries[0].Title != "新標題" || len(doc.Entries[0].UniqueIDs) != 1 || doc.Entries[0].UniqueIDs[0].Type != "jelee" || !domain.ValidID(doc.Entries[0].UniqueIDs[0].Value) {
		t.Fatal("controlled output or generated ID differs")
	}
	// A new service and adapter instance recovers exactly the stored output, even
	// after the current file is unavailable. Replay is historical preparation,
	// never permission to execute without new filesystem checks.
	if err := os.Remove(filepath.Join(scope.Source.RootPath, scope.Source.RelativePath)); err != nil {
		t.Fatal("remove private fixture")
	}
	b, _ := resources.New(resources.Limits{CPU: 1, IO: 1, Total: 1, Queue: 0})
	p, _ := nfo.NewWritePreparer(b)
	fresh, err := Open(f.ctx, f.s.Pool.Config().ConnString(), 2)
	if err != nil {
		t.Fatal("reopen preparation repository")
	}
	defer fresh.Pool.Close()
	service, _ = app.NewNFOWritePreparations(fresh, p)
	old, replay, err := service.Prepare(f.ctx, f.a, "freeze-output", request)
	if err != nil || !replay || old.ID != prepared.ID || !bytes.Equal(old.Replacement, prepared.Replacement) || !bytes.Equal(old.Original, prepared.Original) {
		t.Fatal("replay regenerated bytes or ID")
	}
	old.Replacement[0] = 0
	old.Request.Edits[0].Value = "caller"
	old, replay, err = service.Prepare(f.ctx, f.a, "freeze-output", request)
	if err != nil || !replay || !bytes.Equal(old.Replacement, prepared.Replacement) || old.Request.Edits[0].Value != request.Edits[0].Value {
		t.Fatal("caller mutation reached retained intent")
	}
	request.Edits[0].Value = "different"
	if _, _, err := service.Prepare(f.ctx, f.a, "freeze-output", request); err != domain.ErrConflict {
		t.Fatal("different request replayed")
	}
	var rows, audits int
	var safeAudit bool
	if err := f.s.Pool.QueryRow(f.ctx, `SELECT count(*),(SELECT count(*) FROM audit_logs WHERE event='nfo.write_prepared'),(SELECT bool_and(NOT (COALESCE(after_state::text,'') LIKE '%vendor%' OR COALESCE(after_state::text,'') LIKE '%rootPath%')) FROM audit_logs WHERE event='nfo.write_prepared') FROM nfo_write_preparations`).Scan(&rows, &audits, &safeAudit); err != nil || rows != 1 || audits != 1 || !safeAudit {
		t.Fatal("replay changed retained rows or private audit")
	}
	encoded, _ := json.Marshal(prepared)
	if string(encoded) != "{}" || strings.Contains(fmt.Sprintf("%+v %#v", prepared, prepared), scope.Source.RootPath) {
		t.Fatal("private output leaked through diagnostics")
	}
	if _, err := f.s.Pool.Exec(f.ctx, `UPDATE sessions SET revoked_at=clock_timestamp() WHERE id=$1::uuid`, f.a.SessionID); err != nil {
		t.Fatal("revoke replay session")
	}
	request.Edits[0].Value = "新標題"
	if value, replay, err := service.Prepare(f.ctx, f.a, "freeze-output", request); err != domain.ErrUnauthenticated || replay || value.ID != "" || len(value.Replacement) > 0 {
		t.Fatal("revoked session replayed private output")
	}
}

func TestNFOWritePreparationConcurrentReplayStoresOneOutput(t *testing.T) {
	f, service, scope, request := nfoWritePreparationFixture(t)
	mediaPath := filepath.Join(scope.Source.RootPath, filepath.FromSlash(scope.MediaPath))
	mediaBefore, err := os.ReadFile(mediaPath)
	if err != nil {
		t.Fatal("read owned media fixture")
	}
	var wg sync.WaitGroup
	start := make(chan struct{})
	type result struct {
		value  domain.NFOWritePreparation
		replay bool
		err    error
	}
	results := make(chan result, 12)
	for range 12 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			v, r, e := service.Prepare(f.ctx, f.a, "same-intent", request)
			results <- result{v, r, e}
		}()
	}
	close(start)
	wg.Wait()
	close(results)
	var first domain.NFOWritePreparation
	created := 0
	for r := range results {
		if r.err != nil {
			t.Fatal("concurrent preparation failed")
		}
		if !r.replay {
			created++
		}
		if first.ID == "" {
			first = r.value
		}
		if r.value.ID != first.ID || !bytes.Equal(r.value.Replacement, first.Replacement) {
			t.Fatal("concurrent retry chose another ID or output")
		}
	}
	if created != 1 {
		t.Fatal("more than one preparation committed")
	}
	after, _ := os.ReadFile(filepath.Join(scope.Source.RootPath, scope.Source.RelativePath))
	entries, _ := os.ReadDir(scope.Source.RootPath)
	mediaAfter, mediaErr := os.ReadFile(mediaPath)
	if !bytes.Equal(after, first.Original) || len(entries) != 2 || mediaErr != nil || !bytes.Equal(mediaBefore, mediaAfter) {
		t.Fatal("preparation performed a filesystem write")
	}
}

func TestNFOWritePreparationRechecksScopeAndAuthorizationAndAuditRollback(t *testing.T) {
	for _, change := range []string{"generation", "root", "source", "revision", "policy", "session", "audit"} {
		t.Run(change, func(t *testing.T) {
			f, _, scope, request := nfoWritePreparationFixture(t)
			b, _ := resources.New(resources.Limits{CPU: 1, IO: 1, Total: 1, Queue: 0})
			p, _ := nfo.NewWritePreparer(b)
			prepared, err := p.PrepareNFOWrite(f.ctx, scope, request)
			if err != nil {
				t.Fatal("prepare bytes")
			}
			query := map[string]string{
				"generation": `UPDATE libraries SET nfo_generation=nfo_generation+1`,
				"root":       `UPDATE library_roots SET path=path||'/changed'`,
				"source":     `UPDATE media_sources SET relative_path='changed.mkv'`,
				"revision":   `UPDATE item_metadata_state SET revision=revision+1`,
				"policy":     `UPDATE libraries SET nfo_mode='off',nfo_generation=nfo_generation+1`,
				"session":    `UPDATE sessions SET revoked_at=clock_timestamp()`,
				"audit":      `CREATE FUNCTION reject_prepared_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.event='nfo.write_prepared' THEN RAISE EXCEPTION 'private fixture rejection'; END IF; RETURN NEW; END $$; CREATE TRIGGER reject_prepared_audit BEFORE INSERT ON audit_logs FOR EACH ROW EXECUTE FUNCTION reject_prepared_audit()`,
			}[change]
			if change == "revision" {
				title := "changed title"
				metadata, err := f.s.UpdateItemMetadata(f.ctx, f.a, scope.ItemID, 1, []domain.ItemMetadataPatch{{Field: "title", Value: &title}})
				if err != nil || metadata.Revision != 2 {
					t.Fatal("revision did not change through application contract")
				}
			} else if _, err := f.s.Pool.Exec(f.ctx, query); err != nil {
				t.Fatal("prepare mutation fixture")
			}
			value, replay, err := f.s.SaveNFOWritePreparation(f.ctx, f.a, "stale", prepared)
			if err == nil || replay || value.ID != "" || len(value.Replacement) > 0 {
				t.Fatal("invalidated preparation committed or leaked partial bytes")
			}
			var rows, audits int
			if err := f.s.Pool.QueryRow(f.ctx, `SELECT count(*),(SELECT count(*) FROM audit_logs WHERE event='nfo.write_prepared') FROM nfo_write_preparations`).Scan(&rows, &audits); err != nil || rows != 0 || audits != 0 {
				t.Fatal("rejection did not roll back preparation and audit")
			}
		})
	}
}

func TestNFOWritePreparationActorQuotaAndImmutableStorage(t *testing.T) {
	f, service, _, request := nfoWritePreparationFixture(t)
	first, replay, err := service.Prepare(f.ctx, f.a, "quota-0", request)
	if err != nil || replay {
		t.Fatal("first preparation")
	}
	for i := 1; i < 32; i++ {
		if _, _, err := f.s.SaveNFOWritePreparation(f.ctx, f.a, fmt.Sprintf("quota-%d", i), first); err != nil {
			t.Fatal("capacity rejected below actor limit")
		}
	}
	if value, replay, err := f.s.SaveNFOWritePreparation(f.ctx, f.a, "quota-over", first); err != domain.ErrNFOCacheCapacity || replay || value.ID != "" {
		t.Fatal("actor capacity not enforced")
	}
	if _, replay, err := service.Prepare(f.ctx, f.a, "quota-0", request); err != nil || !replay {
		t.Fatal("full capacity rejected exact replay")
	}
	for _, query := range []string{
		`UPDATE nfo_write_preparations SET replacement_bytes=convert_to('<movie/>','UTF8')`,
		`UPDATE nfo_write_preparations SET generation=generation+1`,
		`UPDATE nfo_write_preparations SET expires_at=expires_at+interval '1 second'`,
		`UPDATE nfo_write_preparations SET idempotency_key='other'`,
	} {
		_, err := f.s.Pool.Exec(f.ctx, query)
		jobMetricMigrationRejected(t, err)
	}
	// INSERT trigger also rejects direct SQL above the actor bound.
	_, err = f.s.Pool.Exec(f.ctx, `INSERT INTO nfo_write_preparations SELECT (jsonb_populate_record(NULL::nfo_write_preparations,to_jsonb(p)||jsonb_build_object('id',gen_random_uuid(),'idempotency_key','direct-over'))).* FROM nfo_write_preparations p LIMIT 1`)
	jobMetricMigrationRejected(t, err)
	var count int
	if err := f.s.Pool.QueryRow(f.ctx, `SELECT count(*) FROM nfo_write_preparations`).Scan(&count); err != nil || count != 32 {
		t.Fatal("rejected mutation changed storage")
	}
}

func TestNFOWritePreparationExpiredRowsReclaimedAndSQLShapeRejected(t *testing.T) {
	f, service, _, request := nfoWritePreparationFixture(t)
	first, _, err := service.Prepare(f.ctx, f.a, "retained-live", request)
	if err != nil {
		t.Fatal("prepare live output")
	}
	_, err = f.s.Pool.Exec(f.ctx, `INSERT INTO nfo_write_preparations
 SELECT (jsonb_populate_record(NULL::nfo_write_preparations,to_jsonb(p)||jsonb_build_object('id',gen_random_uuid(),'idempotency_key','expired-'||n,'created_at','2020-01-01 00:00:00+00','expires_at','2020-01-02 00:00:00+00'))).*
 FROM nfo_write_preparations p CROSS JOIN generate_series(1,31) n WHERE p.id=$1::uuid`, first.ID)
	if err != nil {
		t.Fatal("create bounded expired fixture")
	}
	digest, _ := domain.NFOWriteRequestDigest(request)
	if _, err := f.s.FindNFOWritePreparation(f.ctx, f.a, "expired-31", digest); err != domain.ErrNotFound {
		t.Fatal("expired output replayed")
	}
	value, replay, err := f.s.SaveNFOWritePreparation(f.ctx, f.a, "expired-31", first)
	if err != nil || replay || value.ID == first.ID {
		t.Fatal("expired actor slots did not recover")
	}
	var rows, audits int
	if err := f.s.Pool.QueryRow(f.ctx, `SELECT count(*),(SELECT count(*) FROM audit_logs WHERE event='nfo.write_prepared') FROM nfo_write_preparations`).Scan(&rows, &audits); err != nil || rows != 2 || audits != 2 {
		t.Fatal("expiry cleanup affected live data or audit")
	}
	for _, patch := range []string{
		`jsonb_build_object('version',2)`,
		`jsonb_build_object('original_sha256','bad')`,
		`jsonb_build_object('replacement_sha256','bad')`,
		`jsonb_build_object('max_bytes',0)`,
		`jsonb_build_object('revision',2147483647)`,
		`jsonb_build_object('request_bytes',convert_to('{}','UTF8'),'request_digest',encode(sha256(convert_to('{}','UTF8')),'hex'))`,
		`jsonb_build_object('expires_at','infinity')`,
		`jsonb_build_object('expires_at',p.created_at+interval '25 hours')`,
	} {
		query := `INSERT INTO nfo_write_preparations SELECT (jsonb_populate_record(NULL::nfo_write_preparations,to_jsonb(p)||jsonb_build_object('id',gen_random_uuid(),'idempotency_key','invalid-copy')||` + patch + `)).* FROM nfo_write_preparations p WHERE p.id=$1::uuid`
		_, err := f.s.Pool.Exec(f.ctx, query, first.ID)
		jobMetricMigrationRejected(t, err)
	}
}

func TestNFOWritePreparationLibraryByteCapacity(t *testing.T) {
	f, service, _, request := nfoWritePreparationFixture(t)
	first, _, err := service.Prepare(f.ctx, f.a, "byte-base", request)
	if err != nil {
		t.Fatal("prepare byte fixture")
	}
	// Generate large bytes inside PostgreSQL, without printing or returning them.
	// One row has two exact 32MiB documents. The second exceeds the 128MiB library
	// cap once recipes and the existing small row are included.
	query := `WITH large AS MATERIALIZED (SELECT convert_to(rpad('<movie/>',33554432,' '),'UTF8') AS value), recipe AS MATERIALIZED (SELECT p.*,convert_to((convert_from(request_bytes,'UTF8')::jsonb||jsonb_build_object('maxBytes',33554432))::text,'UTF8') AS encoded FROM nfo_write_preparations p WHERE id=$1::uuid)
 INSERT INTO nfo_write_preparations(id,actor_id,idempotency_key,version,request_bytes,request_digest,library_id,item_id,source_id,root_id,kind,revision,generation,root_generation,root_path,relative_path,media_path,directory_path,max_bytes,modified_unix_nano,original_bytes,original_sha256,replacement_bytes,replacement_sha256,native_receipt)
 SELECT gen_random_uuid(),actor_id,$2,version,encoded,encode(sha256(encoded),'hex'),library_id,item_id,source_id,root_id,kind,revision,generation,root_generation,root_path,relative_path,media_path,directory_path,33554432,modified_unix_nano,value,encode(sha256(value),'hex'),value,encode(sha256(value),'hex'),native_receipt FROM recipe CROSS JOIN large`
	if _, err := f.s.Pool.Exec(f.ctx, query, first.ID, "large-one"); err != nil {
		t.Fatal("byte quota rejected below limit")
	}
	_, err = f.s.Pool.Exec(f.ctx, query, first.ID, "large-two")
	jobMetricMigrationRejected(t, err)
	var rows int
	if err := f.s.Pool.QueryRow(f.ctx, `SELECT count(*) FROM nfo_write_preparations`).Scan(&rows); err != nil || rows != 2 {
		t.Fatal("byte capacity failure changed stored rows")
	}
}

func TestNFOWritePreparationMigrationEmptyRoundTripAndRetainedRefusal(t *testing.T) {
	t.Run("empty", func(t *testing.T) {
		f := newJobFixture(t)
		jobMetricMigration(t, f, "down", 46)
		jobMetricMigration(t, f, "down", 45)
		jobMetricMigration(t, f, "up", SchemaVersion)
		if err := f.s.Ready(f.ctx); err != nil {
			t.Fatal("new schema not ready")
		}
	})
	t.Run("retained", func(t *testing.T) {
		f, _, _, request := nfoWritePreparationFixture(t)
		prepared := legacyNFOWritePreparationFixture(t, f, request, "retained", 46)
		if _, _, err := Migrate(f.ctx, f.s.Pool.Config().ConnString(), "down"); err == nil {
			t.Fatal("downgrade discarded prepared output")
		}
		version, dirty, err := Migrate(f.ctx, f.s.Pool.Config().ConnString(), "status")
		if err != nil || version != 45 || !dirty {
			t.Fatal("refused downgrade lost dirty state")
		}
		digest, _ := domain.NFOWriteRequestDigest(request)
		retained, err := f.s.FindNFOWritePreparation(f.ctx, f.a, "retained", digest)
		if err != nil || retained.ID != prepared.ID || !bytes.Equal(retained.Replacement, prepared.Replacement) {
			t.Fatal("refused downgrade changed output")
		}
		if err := f.s.Ready(f.ctx); err == nil {
			t.Fatal("dirty schema accepted")
		}
	})
}
