name: OpenAPI Artifact
on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  publish-openapi:
    name: OpenAPI - Publish Artifact
    uses: ./.github/workflows/openapi-generate.yml
    permissions:
      contents: read
    with:
      ref: ${{ github.sha }}
      repository: ${{ github.repository }}
      artifact: openapi-head
